// GENERATED — do not edit manually

import 'package:flutter/material.dart';
import 'ids_enums.dart';

class IdsTokens {
  IdsTokens._();

  static Color resolve({
    required IdsColor color,
    required IdsMode mode,
    required String token,
  }) {
    return switch ((color, mode)) {
      (IdsColor.amber, IdsMode.dark) => _amberDark[token] ?? Colors.transparent,
      (IdsColor.amber, IdsMode.light) => _amberLight[token] ?? Colors.transparent,
      (IdsColor.blue, IdsMode.dark) => _blueDark[token] ?? Colors.transparent,
      (IdsColor.blue, IdsMode.light) => _blueLight[token] ?? Colors.transparent,
      (IdsColor.cyan, IdsMode.dark) => _cyanDark[token] ?? Colors.transparent,
      (IdsColor.cyan, IdsMode.light) => _cyanLight[token] ?? Colors.transparent,
      (IdsColor.emerald, IdsMode.dark) => _emeraldDark[token] ?? Colors.transparent,
      (IdsColor.emerald, IdsMode.light) => _emeraldLight[token] ?? Colors.transparent,
      (IdsColor.fuchsia, IdsMode.dark) => _fuchsiaDark[token] ?? Colors.transparent,
      (IdsColor.fuchsia, IdsMode.light) => _fuchsiaLight[token] ?? Colors.transparent,
      (IdsColor.green, IdsMode.dark) => _greenDark[token] ?? Colors.transparent,
      (IdsColor.green, IdsMode.light) => _greenLight[token] ?? Colors.transparent,
      (IdsColor.indigo, IdsMode.dark) => _indigoDark[token] ?? Colors.transparent,
      (IdsColor.indigo, IdsMode.light) => _indigoLight[token] ?? Colors.transparent,
      (IdsColor.lime, IdsMode.dark) => _limeDark[token] ?? Colors.transparent,
      (IdsColor.lime, IdsMode.light) => _limeLight[token] ?? Colors.transparent,
      (IdsColor.orange, IdsMode.dark) => _orangeDark[token] ?? Colors.transparent,
      (IdsColor.orange, IdsMode.light) => _orangeLight[token] ?? Colors.transparent,
      (IdsColor.pink, IdsMode.dark) => _pinkDark[token] ?? Colors.transparent,
      (IdsColor.pink, IdsMode.light) => _pinkLight[token] ?? Colors.transparent,
      (IdsColor.purple, IdsMode.dark) => _purpleDark[token] ?? Colors.transparent,
      (IdsColor.purple, IdsMode.light) => _purpleLight[token] ?? Colors.transparent,
      (IdsColor.red, IdsMode.dark) => _redDark[token] ?? Colors.transparent,
      (IdsColor.red, IdsMode.light) => _redLight[token] ?? Colors.transparent,
      (IdsColor.rose, IdsMode.dark) => _roseDark[token] ?? Colors.transparent,
      (IdsColor.rose, IdsMode.light) => _roseLight[token] ?? Colors.transparent,
      (IdsColor.sky, IdsMode.dark) => _skyDark[token] ?? Colors.transparent,
      (IdsColor.sky, IdsMode.light) => _skyLight[token] ?? Colors.transparent,
      (IdsColor.teal, IdsMode.dark) => _tealDark[token] ?? Colors.transparent,
      (IdsColor.teal, IdsMode.light) => _tealLight[token] ?? Colors.transparent,
      (IdsColor.violet, IdsMode.dark) => _violetDark[token] ?? Colors.transparent,
      (IdsColor.violet, IdsMode.light) => _violetLight[token] ?? Colors.transparent,
      (IdsColor.yellow, IdsMode.dark) => _yellowDark[token] ?? Colors.transparent,
      (IdsColor.yellow, IdsMode.light) => _yellowLight[token] ?? Colors.transparent,
    };
  }

  static const _amberDark = <String, Color>{
    'primary': const Color(0xFFE17100),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFF461901),
    'on-secondary': const Color(0xFFFFB900),
    'accent': const Color(0xFFFE9A00),
    'outline': const Color(0xFF973C00),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _amberLight = <String, Color>{
    'primary': const Color(0xFFE17100),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFFFEF3C6),
    'on-secondary': const Color(0xFF973C00),
    'accent': const Color(0xFFBB4D00),
    'outline': const Color(0xFFFEE685),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _blueDark = <String, Color>{
    'primary': const Color(0xFF155DFC),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFF162456),
    'on-secondary': const Color(0xFF51A2FF),
    'accent': const Color(0xFF51A2FF),
    'outline': const Color(0xFF193CB8),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _blueLight = <String, Color>{
    'primary': const Color(0xFF155DFC),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFFDBEAFE),
    'on-secondary': const Color(0xFF1447E6),
    'accent': const Color(0xFF1447E6),
    'outline': const Color(0xFFBEDBFF),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _cyanDark = <String, Color>{
    'primary': const Color(0xFF0092B8),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFF053345),
    'on-secondary': const Color(0xFF00D3F2),
    'accent': const Color(0xFF00B8DB),
    'outline': const Color(0xFF005F78),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _cyanLight = <String, Color>{
    'primary': const Color(0xFF0092B8),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFFCEFAFE),
    'on-secondary': const Color(0xFF005F78),
    'accent': const Color(0xFF007595),
    'outline': const Color(0xFFA2F4FD),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _emeraldDark = <String, Color>{
    'primary': const Color(0xFF009966),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFF002C22),
    'on-secondary': const Color(0xFF00D492),
    'accent': const Color(0xFF00BC7D),
    'outline': const Color(0xFF006045),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _emeraldLight = <String, Color>{
    'primary': const Color(0xFF009966),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFFD0FAE5),
    'on-secondary': const Color(0xFF006045),
    'accent': const Color(0xFF007A55),
    'outline': const Color(0xFFA4F4CF),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _fuchsiaDark = <String, Color>{
    'primary': const Color(0xFFC800DE),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFF4B004F),
    'on-secondary': const Color(0xFFED6AFF),
    'accent': const Color(0xFFED6AFF),
    'outline': const Color(0xFF8A0194),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _fuchsiaLight = <String, Color>{
    'primary': const Color(0xFFC800DE),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFFFAE8FF),
    'on-secondary': const Color(0xFFA800B7),
    'accent': const Color(0xFFA800B7),
    'outline': const Color(0xFFF6CFFF),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _greenDark = <String, Color>{
    'primary': const Color(0xFF418501),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFF0F2400),
    'on-secondary': const Color(0xFF4ADE5E),
    'accent': const Color(0xFF22C53E),
    'outline': const Color(0xFF2A5701),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _greenLight = <String, Color>{
    'primary': const Color(0xFF418501),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFFDCFCDC),
    'on-secondary': const Color(0xFF366E01),
    'accent': const Color(0xFF366E01),
    'outline': const Color(0xFFBBF7BB),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _indigoDark = <String, Color>{
    'primary': const Color(0xFF4F39F6),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFF1E1A4D),
    'on-secondary': const Color(0xFF7C86FF),
    'accent': const Color(0xFF7C86FF),
    'outline': const Color(0xFF372AAC),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _indigoLight = <String, Color>{
    'primary': const Color(0xFF4F39F6),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFFE0E7FF),
    'on-secondary': const Color(0xFF432DD7),
    'accent': const Color(0xFF4F39F6),
    'outline': const Color(0xFFC6D2FF),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _limeDark = <String, Color>{
    'primary': const Color(0xFF5EA500),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFF192E03),
    'on-secondary': const Color(0xFF9AE600),
    'accent': const Color(0xFF7CCF00),
    'outline': const Color(0xFF3C6300),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _limeLight = <String, Color>{
    'primary': const Color(0xFF5EA500),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFFECFCCA),
    'on-secondary': const Color(0xFF3C6300),
    'accent': const Color(0xFF497D00),
    'outline': const Color(0xFFD8F999),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _orangeDark = <String, Color>{
    'primary': const Color(0xFFFF4500),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFF451300),
    'on-secondary': const Color(0xFFFF7650),
    'accent': const Color(0xFFFF5722),
    'outline': const Color(0xFFA32D00),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _orangeLight = <String, Color>{
    'primary': const Color(0xFFFF4500),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFFFFE8DE),
    'on-secondary': const Color(0xFFA32D00),
    'accent': const Color(0xFFA32D00),
    'outline': const Color(0xFFFFC8B4),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _pinkDark = <String, Color>{
    'primary': const Color(0xFFE60076),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFF510424),
    'on-secondary': const Color(0xFFFB64B6),
    'accent': const Color(0xFFFB64B6),
    'outline': const Color(0xFFA3004C),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _pinkLight = <String, Color>{
    'primary': const Color(0xFFE60076),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFFFCE7F3),
    'on-secondary': const Color(0xFFA3004C),
    'accent': const Color(0xFFC6005C),
    'outline': const Color(0xFFFCCEE8),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _purpleDark = <String, Color>{
    'primary': const Color(0xFF9810FA),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFF3C0366),
    'on-secondary': const Color(0xFFC27AFF),
    'accent': const Color(0xFFC27AFF),
    'outline': const Color(0xFF6E11B0),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _purpleLight = <String, Color>{
    'primary': const Color(0xFF9810FA),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFFF3E8FF),
    'on-secondary': const Color(0xFF8200DB),
    'accent': const Color(0xFF9810FA),
    'outline': const Color(0xFFE9D4FF),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _redDark = <String, Color>{
    'primary': const Color(0xFFE7000B),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFF460809),
    'on-secondary': const Color(0xFFFF6467),
    'accent': const Color(0xFFFF6467),
    'outline': const Color(0xFF9F0712),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _redLight = <String, Color>{
    'primary': const Color(0xFFE7000B),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFFFFE2E2),
    'on-secondary': const Color(0xFFC10007),
    'accent': const Color(0xFFC10007),
    'outline': const Color(0xFFFFC9C9),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _roseDark = <String, Color>{
    'primary': const Color(0xFFEC003F),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFF4D0218),
    'on-secondary': const Color(0xFFFF637E),
    'accent': const Color(0xFFFF637E),
    'outline': const Color(0xFFA50036),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _roseLight = <String, Color>{
    'primary': const Color(0xFFEC003F),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFFFFE4E6),
    'on-secondary': const Color(0xFFA50036),
    'accent': const Color(0xFFC70036),
    'outline': const Color(0xFFFFCCD3),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _skyDark = <String, Color>{
    'primary': const Color(0xFF0084D1),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFF052F4A),
    'on-secondary': const Color(0xFF00BCFF),
    'accent': const Color(0xFF00A6F4),
    'outline': const Color(0xFF00598A),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _skyLight = <String, Color>{
    'primary': const Color(0xFF0084D1),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFFDFF2FE),
    'on-secondary': const Color(0xFF00598A),
    'accent': const Color(0xFF0069A8),
    'outline': const Color(0xFFB8E6FE),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _tealDark = <String, Color>{
    'primary': const Color(0xFF009689),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFF022F2E),
    'on-secondary': const Color(0xFF00D5BE),
    'accent': const Color(0xFF00BBA7),
    'outline': const Color(0xFF005F5A),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _tealLight = <String, Color>{
    'primary': const Color(0xFF009689),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFFCBFBF1),
    'on-secondary': const Color(0xFF005F5A),
    'accent': const Color(0xFF00786F),
    'outline': const Color(0xFF96F7E4),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _violetDark = <String, Color>{
    'primary': const Color(0xFF7F22FE),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFF2F0D68),
    'on-secondary': const Color(0xFFA684FF),
    'accent': const Color(0xFFA684FF),
    'outline': const Color(0xFF5D0EC0),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _violetLight = <String, Color>{
    'primary': const Color(0xFF7F22FE),
    'on-primary': const Color(0xFFFFFFFF),
    'secondary': const Color(0xFFEDE9FE),
    'on-secondary': const Color(0xFF7008E7),
    'accent': const Color(0xFF7F22FE),
    'outline': const Color(0xFFDDD6FF),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };

  static const _yellowDark = <String, Color>{
    'primary': const Color(0xFFD08700),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFF432004),
    'on-secondary': const Color(0xFFFDC700),
    'accent': const Color(0xFFF0B100),
    'outline': const Color(0xFF894B00),
    'success': const Color(0xFF4ADE5E),
    'on-success': const Color(0xFF0A0A0A),
    'success-strong': const Color(0xFF4ADE5E),
    'warning': const Color(0xFFFDC700),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFFFDC700),
    'danger': const Color(0xFFFF6467),
    'on-danger': const Color(0xFF0A0A0A),
    'danger-strong': const Color(0xFFFF6467),
    'info': const Color(0xFF00BCFF),
    'on-info': const Color(0xFF0A0A0A),
    'info-strong': const Color(0xFF00BCFF),
  };

  static const _yellowLight = <String, Color>{
    'primary': const Color(0xFFD08700),
    'on-primary': const Color(0xFF0A0A0A),
    'secondary': const Color(0xFFFEF9C2),
    'on-secondary': const Color(0xFF894B00),
    'accent': const Color(0xFFA65F00),
    'outline': const Color(0xFFFFF085),
    'success': const Color(0xFF418501),
    'on-success': const Color(0xFFFFFFFF),
    'success-strong': const Color(0xFF366E01),
    'warning': const Color(0xFFF0B100),
    'on-warning': const Color(0xFF0A0A0A),
    'warning-strong': const Color(0xFF894B00),
    'danger': const Color(0xFFC10007),
    'on-danger': const Color(0xFFFFFFFF),
    'danger-strong': const Color(0xFFC10007),
    'info': const Color(0xFF0069A8),
    'on-info': const Color(0xFFFFFFFF),
    'info-strong': const Color(0xFF0069A8),
  };
}
